version: "2"

volumes:
  local_nginx_vhost: {}
  local_nginx_html: {}
  local_nginx_certs: {}

services:
  nginxproxy:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: nginxproxy_local
    container_name: nginxproxy_local
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./compose/custom_proxy.conf:/etc/nginx/conf.d/custom_proxy.conf:ro
      - local_nginx_certs:/etc/nginx/certs
      - local_nginx_vhost:/etc/nginx/vhost.d
      - local_nginx_html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginxproxy_local_network

networks:
  nginxproxy_local_network:
    name: nginxproxy_local_network
