version: "2"

volumes:
  local_nginx_conf: {}
  local_nginx_vhost: {}
  local_nginx_html: {}
  local_nginx_certs: {}

services:
  nginxproxy:
    image: nginxproxy/nginx-proxy:0.8.0
    container_name: nginxproxy_local
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - local_nginx_certs:/etc/nginx/certs
      - local_nginx_vhost:/etc/nginx/vhost.d
      - local_nginx_html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginxproxy_local_network

networks:
  nginxproxy_local_network:
    name: nginxproxy_local_network
